version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map Nginx on port 80 (inside container) to localhost:3000
    environment:
      - REACT_APP_API_URL=http://backend:5000  # Point to the backend service within Docker network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to the backend directory
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/your_db_name?authSource=admin
      - JWT_SECRET=your_jwt_secret  # Replace with your actual JWT secret
      - SESSION_SECRET=your_session_secret  # Replace with your actual session secret
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
